const BOOKMARK_ACTION_TYPES = {
  TOGGLE_BOOKMARKED: "bookmark/TOGGLE_BOOKMARKED",
  ADD_BOOKMARK_ITEMS: "bookmark/ADD_BOOKMARK_ITEMS",
  REMOVE_BOOKMARK_ITEMS: "bookmark/REMOVE_BOOKMARK_ITEMS",
};

export default BOOKMARK_ACTION_TYPES;
