const SEARCH_ACTION_TYPES = {
  FETCH_SEARCH_DATA_SUCCESS: "search/FETCH_SEARCH_DATA_SUCCESS",
  FETCH_SEARCH_DATA_START: "search/FETCH_SEARCH_DATA_START",
  FETCH_SEARCH_DATA_FAILED: "search/FETCH_SEARCH_DATA_FAILED",
  SEARCH_INPUT: "search/SEARCH_INPUT",
};

export default SEARCH_ACTION_TYPES;
