const MOVIES_ACTION_TYPES = {
  FETCH_MOVIES_START: "movies/FETCH_MOVIES_START",
  FETCH_MOVIES_SUCCESS: "movies/FETCH_MOVIES_SUCCESS",
  FETCH_MOVIES_FAILED: "movies/FETCH_MOVIES_FAILED",
};

export default MOVIES_ACTION_TYPES;
