const TRENDING_ACTION_TYPES = {
  FETCH_TRENDING_START: "trending/FETCH_TRENDING_START",
  FETCH_TRENDING_SUCCESS: "trending/FETCH_TRENDING_SUCCESS",
  FETCH_TRENDING_FAILED: "trending/FETCH_TRENDING_FAILED",
};

export default TRENDING_ACTION_TYPES;
